### ISSUE TITLE
up-to-date prices

### ISSUE THREAD

**Issue by maikvitesse** [jvhaarst/panelscrape#1]
Does the current panel scrape still work?
I see on https://jvhaarst.github.io/panelscrape/ only dates of 21-10-2021.
Will this still be updated? i found it a very useful tool! and i have not yet succeeded to run the program itself (but am working on it)

**Comment by jvhaarst** [comment]
Fixed now, the repo on the server that is serving this was stuck on the wrong branch somehow.

**Comment by maikvitesse** [comment]
nice 👍

**Comment by maikvitesse** [comment]
same problem again by chance?

**Comment by jvhaarst** [comment]
Nah. solargarant scraping  is broken.
I'll have a look later, for now I just ignore it better.

**Comment by maikvitesse** [comment]
So i was monitoring the panel prices for a while, now i'm on the point to order some panels.
But unfortunately it stopped working again, any change you could fix it?
would appreciate it!

**Comment by jvhaarst** [comment]
Fixed !

**Comment by Rimco** [comment]
@jvhaarst Should the scraper still be running on your side or do we need to run it locally nowadays? It looks we have really old data by now.

**Comment by jvhaarst** [comment]
Hi @Rimco ,
As my roof is full of panels since the end of 2020, and I thus don't need it anymore, I kinda lost interest in keeping the scraper up to date.
Feel free to clone the repo, and I could give you a hand in setting things up, but that is the level I have time and energy for right now.

**Comment by Rimco** [comment]
I know the feeling with such projects ;) At least clear story. In the meantime I have already found the panels I need and then it's also getting really full on our side so I will leave that exercise to somebody else :)
